lc_subject_field.settings:
  type: config_object
  label: 'Settings'
  mapping:
    base_url:
      type: uri
      label: 'Base URL'
    grid_url:
      type: uri
      label: 'Wikidata URL'
    funder_url:
      type: uri
      label: 'Funder URL'
